name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Windows, Ubuntu, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
